# Experiment config
weights_dir: ./weights
experiment_code: 001A
num_epochs: 12

# Get dataset and dataloaders
data:
  name: IHDataset
  path: ../data/windowed/
  classes: [noIH, IH]
  num_workers: 8
  batch_size: 128

# Initialize model
model:
  name: resnet18
  feature_extract: False #False, finetune the whole model. True, only update new layer params
  use_pretrained: True
  print_model: True
# Get optimizer
optimizer:
  name: SGD
  lr: 0.02
  momentum: 0.9
  weight_decay: 0.001
  print_params: True

# Get criterion
criterion:
  name: CrossEntropyLoss

# Get scheduler
scheduler:
  name: StepLR
  step_size: 2
  gamma: 0.5
