# Experiment config
task: evaluation
experiments_dir: ./experiments
experiment_code: R34_001
metrics: False
grad_cam: True

# Get dataset and dataloaders
data:
  name: IHDataset
  path: ../data/windowed/
  classes: [noIH, IH]
  num_workers: 4
  batch_size: 4

# Initialize model
model:
  name: resnet34
  feature_extract: False #False, finetune the whole model. True, only update new layer params
  use_pretrained: True
  print_model: False