# Experiment config
task: evaluation
experiments_dir: ./experiments
experiment_code: EFFDET_003
metrics: False
grad_cam: True

# Get dataset and dataloaders
data:
  name: IHDataset
  path: ../data/windowed/
  classes: [noIH, IH]
  num_workers: 8
  batch_size: 8

# Initialize model
model:
  name: efficientdet_d0
  feature_extract: False #False, finetune the whole model. True, only update new layer params
  use_pretrained: True
  print_model: False