# Experiment config
task: training
experiments_dir: ./experiments
experiment_code: R50_002
num_epochs: 4

# Get dataset and dataloaders
data:
  name: IHDataset
  path: ../data/windowed/
  classes: [noIH, IH]
  num_workers: 8
  batch_size: 32

# Initialize model
model:
  name: resnet50
  feature_extract: False #False, finetune the whole model. True, only update new layer params
  use_pretrained: True
  print_model: False

# Get optimizer
optimizer:
  name: SGD
  lr: 0.02
  momentum: 0.9
  weight_decay: 0.001
  print_params: False

# Get criterion
criterion:
  name: CrossEntropyLoss

# Get scheduler
scheduler:
  name: StepLR
  step_size: 1
  gamma: 0.5
